### ISSUE TITLE
Doesn't working with node 8.1.x

### ISSUE THREAD

**Issue by ralvs** [scravy/node-macaddress#14]
.one(callback) = return a mac that doesn't exists in my pc

.one('en1', callback) = return the right mac but it repeats every 1 second, indefinitely

.all(callback) = print the correct ip of the active interface but the wrong mac, and repeats every 1 second, indefinitely

I'm running macOS Sierra 10.12.5 in an old macbook pro

**Comment by scravy** [comment]
Since this report is three years old and I have not heard any complaints about this one, I am closing this.

As far as I can see it works across a wide range of node versions and platforms, as can be seen in the travis logs.

Feel free to comment and/or reopen should this occur again.
