### ISSUE TITLE
Wrong Address

### ISSUE THREAD

**Issue by japita-se** [scravy/node-macaddress#15]
```
>  var gc                 = require('macaddress');
undefined
> gc.networkInterfaces()
{ wlan0: 
   { ipv4: '169.254.126.229',
     mac: 'b8:27:eb:a5:16:d4',
     ipv6: 'fe80::e1bf:48cf:786c:ee08' } }
```

But my net is:
```


wlan0     Link encap:Ethernet  HWaddr b8:27:eb:a5:16:d4  
          inet addr:192.168.1.149  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::e1bf:48cf:786c:ee08/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:47240 errors:0 dropped:37 overruns:0 frame:0
          TX packets:26971 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:17212206 (16.4 MiB)  TX bytes:13238658 (12.6 MiB)
```

**Comment by ihabhamad** [comment]
wlan0     Link encap:Ethernet  HWaddr {b8:27:eb:a5:16:d4}
the same output    mac: 'b8:27:eb:a5:16:d4',

**Comment by scravy** [comment]
That looks exactly right to me. The mac address / hardware addresses match (`b8:27:eb:a5:16:d4` – you running a raspberry pi B827EB?), your ipv6 address is correct, and if you're worrying about the inet addresses reported – both of them are link-local addresses so you are probably and actually reachable in your local network at both these adresses. Not sure why node reports the one while `ifconfig` reports the other.

This package is mainly about the macaddress of a machine.
