### ISSUE TITLE
Does not return any MAC addresses when offline

### ISSUE THREAD

**Issue by arthurakay** [scravy/node-macaddress#2]
I've been using this module in a project, and users have reported problems on various platforms -- the problems all boil down to my use of `macaddress`, but only when their machines are offline.

I haven't been able to reproduce the issue personally on OSX, but on Windows 8.1 I see the problem.

```
mac.all(function (err, all) {
    for (var prop in all) {
        console.log(all[ prop ].mac); //will always be blank output when offline
    }
});
```

To be clear, my Windows 8.1 machine does not have WIFI -- it only uses a hard ethernet connection. Removing that hard line is when I see the issue.

**Comment by scravy** [comment]
I have tested the library in a Windows XP machine and it worked quite well. Which version of node/iojs are you using? Could you give me the output of `require('os').networkInterfaces()`?

**Comment by arthurakay** [comment]
Using Node v0.10.38 from my Command Prompt, I get the following:

When connected to hardwire internet:

```
    > require('os').networkInterfaces()
    { Ethernet:
       [ { address: '2601:245:4200:c772:31da:e934:7671:1a70',
           family: 'IPv6',
           internal: false },
         { address: '2601:245:4200:c772:65ed:8db0:3de9:91fd',
           family: 'IPv6',
           internal: false },
         { address: 'fe80::31da:e934:7671:1a70',
           family: 'IPv6',
           internal: false },
         { address: '10.0.0.11',
           family: 'IPv4',
           internal: false } ],
      'Loopback Pseudo-Interface 1':
       [ { address: '::1',
           family: 'IPv6',
           internal: true },
         { address: '127.0.0.1',
           family: 'IPv4',
           internal: true } ],
      'Teredo Tunneling Pseudo-Interface':
       [ { address: '2001:0:5ef5:79fd:c20:1fe:f5ff:fff4',
           family: 'IPv6',
           internal: false },
         { address: 'fe80::c20:1fe:f5ff:fff4',
           family: 'IPv6',
           internal: false } ] }
```

When I disconnect the hardwire, I see this:

```
    > require('os').networkInterfaces()
    { 'Loopback Pseudo-Interface 1':
       [ { address: '::1',
           family: 'IPv6',
           internal: true },
         { address: '127.0.0.1',
           family: 'IPv4',
           internal: true } ] }
```

So yes, this is Node 0.10.x -- but I also notice the problem when running the command from inside the [Electron](https://github.com/atom/electron) shell, which (I think) runs the latest io.js.

**Comment by scravy** [comment]
Hm, okay. So the way it currently works is:
- (1) get a list of interfaces via `networkInterfaces()` (excluding the loopback device)
- (2) get mac addresses for these, in node 0.12+ they are already reported, if mac address is not reported check using an OS-dependent tool (`ifconfig` in Unix, etc.).

In your case it fails in (1).

Maybe I should add some means of getting that list of networkInterfaces in an OS-dependent manner if the list in (1) is empty.

**Comment by arthurakay** [comment]
Just curious if you made any progress on this. I'm finally circling back to the issue myself, so please let me know if there is anything else I can help with.

**Comment by scravy** [comment]
I do not have access to a windows machine right now :-( so I could not start to work on that. It's still on my radar though.

**Comment by McPo** [comment]
This is an issue across all OS's (OSX El Capitan, Ubuntu 14.04, Windows 7 and Windows 10).

Heres a method which works across all those listed OS (Its ugly but works).

```
ifconfig -l                     #OSX
ls /sys/class/net               #UBUNTU
wmic nic get NetConnectionID    #WINDOWS
```

Loopback Names

```
lo0                         # OSX
lo                          # UBUNTU
Loopback Pseudo-Interface 1 # WINDOWS
```

OSX need to remove loopback

```
require('child_process').exec('ifconfig -l', (error, stdout, stderr) => { console.log(stdout.trim().split(' ')); });
```

Ubuntu need to remove loopback

```
 require('child_process').exec('ls /sys/class/net', (error, stdout, stderr) => { console.log(stdout.trim().split('\n')); })
```

Windows no need to remove loopback and it isn't returned in this command

```
require('child_process').exec('wmic nic get NetConnectionID', (error, stdout, stderr) => { console.log(stdout.trim().replace(/\s{2,}/g, '\n').split('\n').slice(1))})
```

**Comment by McPo** [comment]
For those suffering this issue. Heres a hacky workaround for the .one() method

```
static getInterface() {
        const getAllInterfaces = () => {
            if (process.platform === 'darwin') return childProcess.execSync('ifconfig -l').toString().trim().split(' ');
            else if (process.platform === 'win32') return childProcess.execSync('wmic nic get NetConnectionID').toString().trim().replace(/\s{2,}/g, '\n').split('\n').slice(1);
            else return childProcess.execSync('ls /sys/class/net').toString().trim().split('\n');
        };

        const ifaces = getAllInterfaces();
        const alleged = ['eth0', 'eth1', 'en0', 'en1'];
        let iface = ifaces[0];
        for (let i = 0; i < alleged.length; i++) {
            if (ifaces.indexOf(alleged[i]) !== -1) {
                iface = alleged[i];
                break;
            }
        }
        return iface;
    }
```

Then call

```
macaddress.one(Utils.getInterface(), (err, mac) => {} ));
```

It uses the same logic employed by the .one() method (And any of its warts).

Ive tested it on the above platforms and its works fine.

**Comment by scravy** [comment]
Has been fixed in https://github.com/scravy/node-macaddress/releases/tag/0.5.0 and is releases as `0.5.0`
