### ISSUE TITLE
Error: no interfaces found

### ISSUE THREAD

**Issue by achabill** [scravy/node-macaddress#21]
Mac version: 10.13.4 
Node version: v9.8.0
Mac address version: 0.2.9
React Js: 15.6.2

**Comment by scravy** [comment]
Thank you for your bug report!

Are you online or offline when this happens?

**Comment by achabill** [comment]
Online and offline.

**Comment by achabill** [comment]
It works with pure node but does not work inside my React JS app.

**Comment by scravy** [comment]
...react js. Is your react js app running on the server or as a single page app?

**Comment by achabill** [comment]
On a server

**Comment by scravy** [comment]
You are saying your react js app is running the backend? server side?

**Comment by achabill** [comment]
@scravy I realized I didn't need a mac address. 
But for the sake of this issue, I have a Laravel REST backend and a react front end created with [create-react-app](https://github.com/facebook/create-react-app)

```
import macaddress from "macaddress";
...
 macaddress.one((err, macAddress) => {
      if (err) {
        console.log(err); //err, no interfaces found
        ...
      }
}
```

**Comment by scravy** [comment]
`macaddress` can be used in the backend only. There is no way to read the macaddress from the client's browser, and that's a good thing.
