### ISSUE TITLE
Why not support Promise?

### ISSUE THREAD

**Issue by Jungwoo-An** [scravy/node-macaddress#24]
Promise is very useful for high readability code. why not support?
If possible, i want to submit a pull request for this issue

**Comment by scravy** [comment]
It's possible, submit a pull request. I for one did not have the time to add any more features beyond maintenance / reviewing.

Feel free to add!

**Comment by Jungwoo-An** [comment]
#25 merged

**Comment by scravy** [comment]
Thank you for the contribution of typescript definitions, but what do typescript definitions have to do with an API that uses Promises?!

**Comment by Jungwoo-An** [comment]
Oh, sorry. i closed by mistake

**Comment by scravy** [comment]
The Pull Request has been merged and I released the package as [`0.4.0`](https://github.com/scravy/node-macaddress/releases/tag/0.4.0)
