### ISSUE TITLE
linux implementation can read arbitrary files

### ISSUE THREAD

**Issue by mlc** [scravy/node-macaddress#27]
https://github.com/scravy/node-macaddress/blob/63b9f87d10e98d5b976fa991cb881ae2373c9264/lib/linux.js#L4

By prepending `../../..` to the "interface" name, this line of code can be asked read a file from anywhere on the filesystem as long as that file is named `address`.

It is also a little bit strange to run `cat` to read a file rather than just using the node `fs` module, but patching only that will not solve the security problem.

**Comment by scravy** [comment]
There used to be a very old and ancient version of node which for whatever reason did not read the contents of textfiles in `/sys` properly, which is why `cat` was used.

The name of the interface could well be sanitized.

Do you mind opening a pull request?

**Comment by scravy** [comment]
Has been fixed and released in `v0.4.3`

**Comment by mlc** [comment]
thanks, @scravy!
