### ISSUE TITLE
Cut new release with Typescript definitions

### ISSUE THREAD

**Issue by danawoodman** [scravy/node-macaddress#28]
Seems like a recent commit added Typescript definitions but no release was cut after? Could we have a new release for this so I don't need to copy/paste the definitions?

**Comment by renjithspace** [comment]
I can see the type definitions in the repo but not reflected on the NPM package. Please release a new version to NPM.😭

**Comment by hanktrizz** [comment]
I second this. Please release a new version to NPM please.

**Comment by scravy** [comment]
Has been released as [`0.3.0`](https://github.com/scravy/node-macaddress/releases/tag/0.3.0).
