### ISSUE TITLE
macaddress.one reporting virtualbox port

### ISSUE THREAD

**Issue by cdburke** [scravy/node-macaddress#32]
On linux mint 19.3, node 12.16.1 - 

On my desktop until recently, macaddress.one reported the address from the ethernet port used for external networking.

However, the latest version reports the address from a virtualbox port, vboxnet0, of "0a:00:27:00:00:00" (the usual for virtualbox).

Could macaddress.one recognize and not use the virtualbox address?

**Comment by scravy** [comment]
I pushed a fix. Will release as `0.5.1`.
