### ISSUE TITLE
Works on Localhost but not when deployed

### ISSUE THREAD

**Issue by thelionleo** [scravy/node-macaddress#35]
I get the same macaddress of: 02:b0:82:ce:73:ec
regardless of which device I login to. My app is deployed on Amazon EC2 and I use cloudflare. Is there a possibility that cloudflare may have interfered?

**Comment by scravy** [comment]
I assume `02:b0:82:ce:73:ec` is the value that you get when you deploy your application in EC2? This should be the mac address of the ec2 instance the app is running on (of the ENI attached to your EC2 instance to be exact). Are you saying you get that same value no matter which ec2 instance you deployed your application to?

The mac address is not the client's mac address, but the server's which is running the application. Cloudflare has nothing to do with it.

**Comment by scravy** [comment]
From what I guess from your report: Do you expect to see the client's mac address, i.e. your mac address when you access your service? If so, this is a misunderstanding of what this package does. It reports the mac address of the machine that the node-js script is running on. This can be used for instance for the generation of correct v1 uuids (in fact, this was the primary motivation for it). If you're expecting to see the mac address of your machine when you access your node service on an ec2 machine behind cloudflare you will see the address from that ec2 instance. The mac address you're reporting does look to me like one that an ec2 instance would have.

The mac address is not like for example the ip address which was used to do the request.

I just deployed node-macaddress on an ec2 t2 instance running aws linux myself to see whether it behaves in any way different from what one would expect, everyything works fine according to what I can see.

I am going to close this issue. If you still think that this _is_ a bug please also report the operating system your ec2 instance is running so we can have a look at the interfaces and what macaddress _should_ be reported. You can also go to the ec2 console and check which ENIs have been attached to said machine and see their macaddresses there.
