### ISSUE TITLE
It will be great if getAllInterfaces method is public.

### ISSUE THREAD

**Issue by alinalexandru** [scravy/node-macaddress#36]
`os.networkInterfaces()` returns only informations about interfaces that have IP set.
`lib.one` supports to get the mac address of an interface that doesn't have the IP set, because is using internally `getAllInterfaces`.

My problem is that I need the mac address of an adapter that is not returned by `lib.networkInterfaces`, because is using internally `os.networkInterfaces()`.

**Comment by scravy** [comment]
It should be publicly available already: https://github.com/scravy/node-macaddress/blob/master/index.js#L8

**Comment by Alexander-Taran** [comment]
```ts
async triageQuestion(id) =>{
 respondSameDay()
 let response = await getResponseFromOP( { timeout : fromYears(1) } )
 if(!response) {
    closeQuestion(id,randomReason())
 }
}
```

**Comment by scravy** [comment]
Closing, the discusses function is already publicly exposed as part of the API of this package.
