### ISSUE TITLE
Please release version 0.2.9

### ISSUE THREAD

**Issue by nerdbeere** [scravy/node-macaddress#7]
Hey there,

your package is used in [uniqid](https://github.com/adamhalasz/uniqid) which I use in my project. Unfortunately my project is stuck with node 4 (thanks aws) and I need to use the `--use_strict` flag to start my application.

The version 0.2.8 of your package contains an error which is fixed in the current master: https://github.com/scravy/node-macaddress/blob/0.2.8/index.js#L34

This only fails when strict mode is turned on.

Would be super awesome if you could just release 0.2.9. This would solve my issue immediately.

**Comment by stevenvachon** [comment]
I'm getting global leak errors, caused by the exact same line, when using `--check-leaks` with [mocha](https://npmjs.com/mocha).

**Edit**: This doesn't seem to happen with mocha any more.

**Comment by stevenvachon** [comment]
@scravy please make a release.

**Comment by stevenvachon** [comment]
@scravy wtf

**Comment by stevenvachon** [comment]
@scravy hell-the-fuck-o ?

**Comment by stevenvachon** [comment]
@scravy we would really like this fixed.

**Comment by scravy** [comment]
Version `0.2.9` has been released.
